const data = [
  {
    id: 1,
    title: "Pitchers 3.0",
    subtitle: "1st round starts",
    day: "12",
    startHour: "12",
    startMinute: "59",
    endHour: "14",
    endMinute: "59",
    month: "1",
  },
  {
    id: 2,
    title: "Pitchers 3.0",
    subtitle: "2nd round starts",
    day: "29",
    startHour: "08",
    startMinute: "59",
    endHour: "23",
    endMinute: "59",
    month: "1",
  },

  {
    id: 3,
    title: "The House of Investors",
    subtitle: "Starts Now",
    day: "01",
    startHour: "07",
    startMinute: "59",
    endHour: "23",
    endMinute: "59",
    month: "2",
  },
  {
    id: 4,
    title: "Virtual Trading Competition",
    subtitle: "Starts Now",
    day: "07",
    startHour: "07",
    startMinute: "59",
    endHour: "23",
    endMinute: "59",
    month: "2",
  },
  {
    id: 5,
    title: "Pitchers 3.0",
    subtitle: "Live Pitching",
    day: "11",
    startHour: "16",
    startMinute: "59",
    endHour: "18",
    endMinute: "59",
    month: "2",
  },
  {
    id: 6,
    title: "Connect the Unicorns",
    subtitle: "Quiz",
    day: "12",
    startHour: "08",
    startMinute: "59",
    endHour: "23",
    endMinute: "59",
    month: "2",
  },
  {
    id: 7,
    title: "Musical Night",
    subtitle: "Sing your heart out",
    day: "12",
    startHour: "18",
    startMinute: "59",
    endHour: "20",
    endMinute: "59",
    month: "2",
  },
];

export default data;
