const teamData = [
  {
    id: 1,
    name: "Sujal Barsaiyan",
    imagePath: "/images/team/sujalBarsaiyan.png",
    department: "design",
    email: "sujal.barsaiyan1234@gmail.com",
    instagramLink: "https://www.instagram.com/bettercallsujal/",
    linkedinLink: "https://www.linkedin.com/in/sujal-barsaiyan-51a1b811b/",
    isMember: true,
  },
  {
    id: 2,
    name: "Saket Koppineedi",
    imagePath: "/images/team/saketKoppineedi.jpg",
    department: "event management",
    email: "saketprasad2002@gmail.com",
    instagramLink: "https://www.instagram.com/__kssmp__/",
    linkedinLink: "https://www.linkedin.com/in/saket-koppineedi-87b8b620a",
    isMember: true,
  },
  {
    id: 3,
    name: "Vraj Talati",
    imagePath: "/images/team/vrajTalati.jpg",
    department: "content",
    email: "vrajtalatii@gmail.com",
    instagramLink:
      "https://www.instagram.com/invites/contact/?i=13jri1xodnt43&utm_content=n41nwx0",
    linkedinLink: "https://www.linkedin.com/in/vraj-talati-22286b222",
    isMember: true,
  },
  {
    id: 4,
    name: "Pavankumar",
    imagePath: "/images/team/pavanKumarReddyBhavanam.jpg",
    department: "event management",
    email: "sujal.barsaiyan1234@gmail.com",
    instagramLink: "https://www.instagram.com/pavan_riser_45",
    linkedinLink: "https://www.linkedin.com/in/pavan-kumar-reddy-bhavanam",
    isMember: true,
  },

  {
    id: 5,
    name: "Aayush Patil",
    imagePath: "/images/team/aayushPatil.jpg",
    department: "content",
    email: "bt21cse179@iiitn.ac",
    isMember: true,
  },
  {
    id: 6,
    name: "Prateek Niket",
    imagePath: "/images/team/prateekNiket.jpeg",
    department: "webdev",
    email: "Prateekniket25@gmail.com",
    instagramLink: "https://www.instagram.com/bruhhhh.teek/",
    linkedinLink: "https://www.linkedin.com/in/prateekniket",
    isMember: true,
  },
  {
    id: 19,
    name: "Tanmay Wankhede",
    imagePath: "/images/team/tanmayWankhede.jpg",
    department: "marketing",
    email: "tanmaywkd926@gmail.com",
    instagramLink: "https://www.instagram.com/tanmay_wkd/",
    linkedinLink: "https://www.linkedin.com/in/tanmay-wankhede-454b94214",
    isMember: true,
  },
  {
    id: 20,
    name: "Frey Vegda",
    imagePath: "/images/team/freyVegda.jpeg",
    department: "marketing",
    email: "bt21cse117@iiitn.ac.in",
    instagramLink: "https://www.instagram.com/freyvegda/",
    linkedinLink: "https://www.linkedin.com/in/frey-vegda-6878a1221/",
    isMember: true,
  },
  {
    id: 7,
    name: "Lalitha Tanmai",
    imagePath: "/images/team/tanmaiVaddiparthy.jpg",
    department: "design",
    email: "lalithatanmai@gmail.com",
    instagramLink: "https://www.instagram.com/tanmai_vaddiparthy",
    linkedinLink:
      "https://www.linkedin.com/in/lalitha-tanmai-32b627211/?originalSubdomain=in",
    isMember: true,
  },
  {
    id: 8,
    name: "Hardik Jain",
    imagePath: "/images/team/hardikJain.jpg",
    email: "jainh445@gmail.com",
    instagramLink: "https://instagram.com/haesque_?utm_medium=copy_link",
    linkedinLink: "http://www.linkedin.com/in/hardikjain02",
    isHead: true,
  },
  {
    id: 9,
    name: "Guna Sai kiran",
    imagePath: "/images/team/gunaSaiKiran.jpg",
    department: "design",
    email: "gunasaikiran8055@gmail.com",
    instagramLink: "https://www.instagram.com/bettercallsujal/",
    linkedinLink: "https://www.linkedin.com/in/sujal-barsaiyan-51a1b811b/",
    isMember: true,
  },
  {
    id: 10,
    name: "Neil Dedhia",
    imagePath: "/images/team/neilDedhia.jpg",
    department: "event management",
    email: "neildmdedhia@gmail.com",
    isMember: true,
  },
  {
    id: 11,
    name: "Prateek Singh",
    imagePath: "/images/team/prateekSingh.jpg",
    department: "marketing",
    email: "bt21cse083@iiitn.ac.in",
    instagramLink: "https://instagram.com/prateek.2503?utm_medium=copy_link",
    linkedinLink: "https://www.linkedin.com/in/prateek-singh-812857157",
    isMember: true,
  },
  {
    id: 12,
    name: "Soham Deshpande",
    imagePath: "/images/team/sohamDeshpande.jpg",
    department: "marketing",
    email: "bt21ece083@iiitn.ac.in",
    instagramLink: "https://instagram.com/_soham_243?utm_medium=copy_link",
    isMember: true,
  },
  {
    id: 13,
    name: "Priya Gupta",
    imagePath: "/images/team/priyaGupta.png",
    email: "priyaguptaloha@gmail.com",
    instagramLink: "https://www.instagram.com/priyagupta.star/",
    linkedinLink: "https://www.linkedin.com/in/priya-gupta-117828190/",
    isHead: true,
  },
  {
    id: 14,
    name: "Bhavesh Chaudhari",
    imagePath: "/images/team/bhaveshChaudhari.jpeg",
    department: "Webdev",
    email: "bhic2030@gmail.com",
    instagramLink: "https://instagram.com/bhaveshc0",
    linkedinLink: "https://www.linkedin.com/in/bhavesh-chaudhari-bb4966208/",
    isLead: true,
  },
  {
    id: 15,
    name: "Ritu Bhangale",
    imagePath: "/images/team/rituBhangale.jpeg",
    department: "design",
    email: "ritusbhangale@gmail.com",
    instagramLink: "https://www.linkedin.com/in/ritu-bhangale-11baa9201/",
    linkedinLink: "https://www.linkedin.com/in/ritu-bhangale-11baa9201/",
    isLead: true,
  },
  {
    id: 16,
    name: "Shrishti Shah",
    imagePath: "/images/team/shrishtiShah.jpeg",
    department: "content",
    email: "shrishtishah2002@gmail.com",
    instagramLink: "https://www.instagram.com/_shrishti18_/",
    linkedinLink: "www.linkedin.com/in/shrishti-shah-s18",
    isLead: true,
  },
  {
    id: 17,
    name: "Shubham Kumar",
    imagePath: "/images/team/shubhamKumar.jpg",
    department: "Events & PR",
    email: "bt20ece060@iiitn.ac.in ",
    instagramLink: "https://www.instagram.com/bettercallsujal/",
    linkedinLink: "https://www.linkedin.com/in/sujal-barsaiyan-51a1b811b/",
    isColead: true,
  },
  {
    id: 18,
    name: "Hem Mahimkar",
    imagePath: "/images/team/hemMahimkar.jpg",
    department: "Events & PR",
    linkedinLink: "https://www.linkedin.com/in/hem-mahimkar-307903202/",
    isColead: true,
  },
];

export default teamData;
