export default [
  {
    id: 1,
    title: "Pitching Competition",
    subtitle: "Minimum Viable Product",
    date: "15/01/2022",
    alignText: "align-right",
    dataAos: "fade-left",
  },
  {
    id: 2,
    title: "Pitching Competition",
    subtitle: "Minimum Viable Product",
    date: "15/01/2022",
    alignText: "align-left",
    dataAos: "fade-right",
  },
  {
    id: 3,
    title: "Pitching Competition",
    subtitle: "Minimum Viable Product",
    date: "15/01/2022",
    alignText: "align-right",
    dataAos: "fade-left",
  },
  {
    id: 4,
    title: "Pitching Competition",
    subtitle: "Minimum Viable Product",
    date: "15/01/2022",
    alignText: "align-left",
    dataAos: "fade-right",
  },
  {
    id: 5,
    title: "Pitching Competition",
    subtitle: "Minimum Viable Product",
    date: "15/01/2022",
    alignText: "align-right",
    dataAos: "fade-left",
  },
  {
    id: 6,
    title: "Pitching Competition",
    subtitle: "Minimum Viable Product",
    date: "15/01/2022",
    alignText: "align-left",
    dataAos: "fade-right",
  },
  {
    id: 7,
    title: "Pitching Competition",
    subtitle: "Minimum Viable Product",
    date: "15/01/2022",
    alignText: "align-right",
    dataAos: "fade-left",
  },
];