const data = [
  {
    id: 1,
    title: "Pitchers 3.0",
    subtitle: "1st round starts",
    date: "12/01/2022",
    alignText: "align-right",
    dataAos: "fade-left",
  },
  {
    id: 2,
    title: "Pitchers 3.0",
    subtitle: "1st round ends",
    date: "21/01/2022",
    alignText: "align-left",
    dataAos: "fade-right",
  },
  {
    id: 3,
    title: "Pitchers 3.0",
    subtitle: "2nd Round starts",
    date: "29/01/2022",
    alignText: "align-right",
    dataAos: "fade-left",
  },
  {
    id: 4,
    title: "The House of Investors",
    subtitle: "Begins Now",
    date: "01/02/2022",
    alignText: "align-left",
    dataAos: "fade-right",
  },
  {
    id: 5,
    title: "Pitchers 3.0",
    subtitle: "Second round ends",
    date: "05/02/2022",
    alignText: "align-right",
    dataAos: "fade-left",
  },
  {
    id: 6,
    title: "Speaker Session",
    subtitle: "Coming soon !",
    date: "06/02/2022",
    alignText: "align-left",
    dataAos: "fade-right",
  },
  {
    id: 7,
    title: "Virtual Trading Competition",
    subtitle: "Begins Now",
    date: "07/02/2022",
    alignText: "align-right",
    dataAos: "fade-left",
  },
  {
    id: 8,
    title: "The House of Investors",
    subtitle: "The End",
    date: "08/02/2022",
    alignText: "align-left",
    dataAos: "fade-right",
  },
  {
    id: 9,
    title: "Speaker session",
    subtitle: "Coming soon !",
    date: "09/02/2022",
    alignText: "align-right",
    dataAos: "fade-left",
  },
  {
    id: 10,
    title: "Pitchers 3.0",
    subtitle: "Live Pitching",
    date: "11/02/2022",
    alignText: "align-left",
    dataAos: "fade-right",
  },
  {
    id: 11,
    title: "Connect the Unicorns",
    subtitle: "2 rounds of Quiz",
    date: "12/02/2022",
    alignText: "align-right",
    dataAos: "fade-left",
  },
  {
    id: 12,
    title: "Musical Night",
    subtitle: "Join us & enjoy",
    date: "12/02/2022",
    alignText: "align-left",
    dataAos: "fade-right",
  },
];

export default data;
