export default [
  {
    id: 1,
    title: "Pitching Competition",
    subtitle: "Minimum Viable Product",
    date: "15/01/2022",
    alignText: "align-right",
    dataAos: "fade-left",
  },
  {
    id: 2,
    title: "Case Study Competition",
    subtitle: "Minimum Viable Product",
    date: "15/01/2022",
    alignText: "align-left",
    dataAos: "fade-right",
  },
  {
    id: 3,
    title: "Virtual Trading Competition",
    subtitle: "Minimum Viable Product",
    date: "15/01/2022",
    alignText: "align-right",
    dataAos: "fade-left",
  },
  {
    id: 4,
    title: "Connect the unicorns",
    subtitle: "Minimum Viable Product",
    date: "15/01/2022",
    alignText: "align-left",
    dataAos: "fade-right",
  },
  {
    id: 5,
    title: "Speaker session",
    subtitle: "Minimum Viable Product",
    date: "15/01/2022",
    alignText: "align-right",
    dataAos: "fade-left",
  },
  {
    id: 6,
    title: "Speaker Session",
    subtitle: "Minimum Viable Product",
    date: "15/01/2022",
    alignText: "align-left",
    dataAos: "fade-right",
  },
  {
    id: 7,
    title: "Speaker session",
    subtitle: "Minimum Viable Product",
    date: "15/01/2022",
    alignText: "align-right",
    dataAos: "fade-left",
  },
];